handle_exceptions: false

pagination:
  default_first_page: 1
  articles: 10
  trainers: 10
  galleries: 10
  photos: 10
  videos: 10

articles:
  default_cover_image_url: "/cover_images/default.jpg"
  ealier_articles: 10

trainers:
  default_profile_picture_url: "/profile_pictures/default.jpg"

photos:
  default_image_url: "/images/default.jpg"
